### ISSUE TITLE
window appears on having disconnected the online-mode

### ISSUE THREAD

**Issue by b4zz4** [roelj/inklingreader#41]
On having used the way "online" and having disconnected the inkling this window appears.

SO: GNU/Linux Mint
![2015-12-27-224522_1024x600_scrot](https://cloud.githubusercontent.com/assets/643833/12013032/d2ce9cce-aceb-11e5-9ca5-d7b5893107ba.png)

**Comment by roelj** [comment]
Thanks for trying GNU inklingreader!

This is indeed a bit odd. My inkling device has died, so I cannot test it at the moment. Nevertheless I the last commit fixes this.

Did the online-mode work for you?

**Comment by b4zz4** [comment]
Are Your tested the battery of the pencil?

The on-line way works perfectly
		

Roel Janssen:
> Thanks for trying GNU inklingreader!
> 
> This is indeed a bit odd. My inkling device has died, so I cannot test it at the moment. Nevertheless I the last commit fixes this.
> 
> Did the online-mode work for you?

**Comment by b4zz4** [comment]
Are Your tested the battery of the pencil?

The on-line mode way works perfectly
		

Roel Janssen:
> Thanks for trying GNU inklingreader!
> 
> This is indeed a bit odd. My inkling device has died, so I cannot test it at the moment. Nevertheless I the last commit fixes this.
> 
> Did the online-mode work for you?

**Comment by roelj** [comment]
I ordered a new battery, so it should work again in a week or so.

Glad to hear the online-mode works.
Did the patch/change work for you?

**Comment by cynthia** [comment]
@roelj in case your battery dies again, let me know. I'd be willing to donate a battery or two as a form of gratitude for the great work on the project. (They are a real pain to get, so I got 10 when I had a chance.)

**Comment by b4zz4** [comment]
I have not noticed changes. My computer is slow and is still working well.

Roel Janssen:
> I ordered a new battery, so it should work again in a week or so.
> 
> Glad to hear the online-mode works.
> Did the patch/change work for you?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/roelj/inklingreader/issues/41#issuecomment-167586076
> 

-- 
http://maquinaslibres.tk
gpg: http://ba.zza.pl/bazza.asc

**Comment by roelj** [comment]
@b4zz4 When you compile the latest git version, does the window show up after using online-mode? (Does it solve the reported bug?)

@cynthia Thanks. That is very kind of you. I ordered two, so it should take a while before they die.

**Comment by b4zz4** [comment]
¡Very good!, thanks :D

Roel Janssen:
> @b4zz4 When you compile the latest git version, does the window show up after using online-mode? (Does it solve the reported bug?)
> 
> @cynthia Thanks. That is very kind of you. I ordered two, so it should take a while before they die.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/roelj/inklingreader/issues/41#issuecomment-167768061
> 

-- 
http://maquinaslibres.tk
gpg: http://ba.zza.pl/bazza.asc

**Comment by roelj** [comment]
Thanks for reporting. I think this issue has been resolved now, so I'm closing the bug report.
