### ISSUE TITLE
Configuration file is written location dependent

### ISSUE THREAD

**Issue by dedeibel** [roelj/inklingreader#45]
When I open inklingreader on my linux system (``LC_NUMERIC=de_DE.UTF-8``) and save the config file, the paper size format is written with a comma as decimal point. This can't be read when opening the application again and sketches won't be displayed correctly. Maybe because the page size is recognized as zero.

I'll try to use the same ``setlocale`` code as used for the csv.c code in the repo.

**Comment by dedeibel** [comment]
see https://github.com/roelj/inklingreader/pull/46

**Comment by roelj** [comment]
Thanks a lot for your efforts. I merged your pull-request.
