### ISSUE TITLE
Unable to locate librsvg-2.0

### ISSUE THREAD

**Issue by wout** [roelj/inklingreader#51]
I'm on Pop!_OS 18.10 (Ubuntu based) and I can't find librsvg-2.0. How can it be installed?

**Comment by roelj** [comment]
Looking at [the launchpad entry for librsvg](https://launchpad.net/ubuntu/cosmic/+source/librsvg), I think you'll need:
```
apt-get install librsvg2-dev
```

**Comment by wout** [comment]
That's the one indeed. Thanks! And thanks for keeping the Inkling alive. :)
